public class Car {
            //this is Class body
            //if we change anything in VS code ,in our class
            //sAVE THE FİLE
                //we need to deploy again
            //if you change --> SAVE--> you deploy
            //Got it?
            
            //method name = switchOn
    public void switchOn() {
        System.debug('Starting the car  NOW');
    }
}


//this is outside class